title: Craig Munday
description: Data analytics portfolio and projects
theme: jekyll-theme-minimal
nav:
  - title: "Home"
    url: /
  - title: "Portfolio"
    url: /portfolio
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/craig-munday-773b70367"
